/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package modul4;

import org.flywaydb.core.Flyway;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class App {


    public static void main(String[] args) throws SQLException {


    }

}
